### PR TITLE
Weather downloader

### PR DESCRIPTION
**Pull request by franc90**

### CODE REVIEW

**Comment by jakubiec** [comment]
typo in package name :  pl.edu.agh.awi.downloader.**paramters** ->  should be **parameters**

**Comment by jakubiec** [comment]
You've created an abstract class [AbstractClient](https://github.com/franc90/aviation-weather-integrator/blob/weather-downloader/src/main/java/pl/edu/agh/awi/downloader/AbstractClient.java) without any abstract method and extended it only to call protected method from it. Maybe better approach could be to use delegation than inheritance. I mean, create ClientHelper class with those 2 protected methods as public or package private and reuse this class in all weather info clients?

**Comment by franc90** [comment]
I've made it a little bit more generic, so abstract class suits much better now.

**Comment by jakubiec** [comment]
Yes, now it looks cool and better. Closing.

**Pull request merged**
